# Generated by Django 5.0.6 on 2024-05-27 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular order', primary_key=True, serialize=False)),
                ('date_of_order', models.DateField(blank=True, help_text='Enter the date of the order', null=True)),
                ('status', models.CharField(help_text='Enter the status of the order', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular car', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the car', max_length=200)),
                ('brand', models.CharField(help_text='Enter the brand of the car', max_length=200)),
                ('price', models.CharField(help_text='Enter the price of the car', max_length=200)),
                ('year', models.CharField(help_text='Enter the year of the car', max_length=200)),
                ('order', models.ForeignKey(help_text='Enter the order of the car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.order')),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular buyer', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of the buyer', max_length=200)),
                ('phone', models.CharField(help_text='Enter the phone of the buyer', max_length=200)),
                ('address', models.CharField(help_text='Enter the address of the buyer', max_length=200)),
                ('order', models.ForeignKey(help_text='Enter the order of the buyer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.order')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
